spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skate
    username: skate
    password: skate
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MiPoolHikari
  flyway:
    enabled: true
    locations: classpath:db/migration
